name: "🛠 Quick Code Change"

on:
  workflow_dispatch:
    inputs:
      code-to-change:
        description: 'Specify the code or file to change.'
        required: true
      how-to-change-it:
        description: 'Describe how to change the code.'
        required: true

jobs:
  execute_code_change:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Code Change
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Read the code specified in `code-to-change`.
            2. Apply the changes as described in `how-to-change-it`.
            3. If necessary, use the context variables to inject data from the workflow run.
            4. Commit the changes with a message that describes the change.
