name: "📚 Help with Documentation"

# Triggers the workflow when a label `documentation` is added to an issue
on:
  issues:
    types: [labeled]
    paths:
      - '**/*.md'

jobs:
  documentation-help:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'documentation'
    steps:
      - name: Provide Documentation Help
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Use the `functions.read_github_issue` to read the issue with ID `${{ github.event.issue.number }}`.
            2. Analyze the issue content to understand what needs to be documented.
            3. If the documentation is file-based and can be added to the repository, use `functions.write_file` to create or update the necessary files.
            4. If the documentation cannot be directly added to the repository, compile documentation snippets and use `functions.comment_on_github_issue` to post them as a comment on the issue.
