name: "📝 Maintain Changelog"

on:
  release:
    types: [created]
    
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Update CHANGELOG.md
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Check out the repository.
            2. Identify the previous release tag and the current release tag from the trigger event.
            3. Assemble all commit messages between the new release and the previous one.
            4. Update `CHANGELOG.md` by adding a new section for the current release version and include the assembled commit messages.
            5. Commit the changes to `CHANGELOG.md` with a message following the convention: `Update CHANGELOG.md for <current release version>`.
