name: "🔍 Review New Pull Request"

# Triggers the workflow on new pull request creation
on:
  pull_request:
    types: [opened]

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    outputs:
      task-url: ${{ steps.review.outputs.task-url }}
    steps:
      - name: Handle New PR
        id: review
        uses: PR-Pilot-AI/smart-actions/pr-creation-handler@v1
        with:

          # API key for PR Pilot must be defined as a secret in the repository
          api-key: ${{ secrets.PR_PILOT_API_KEY }}

          # Number of the PR to be handled
          pr-number: ${{ github.event.pull_request.number }}

          # Instructions for handling the PR
          agent-instructions: |
            # How to review Pull Requests

            When reviewing a PR, check the following:
            
            ## Code Quality
            - Code is well-documented
            - Code is well-formatted
            - Code is modular and reusable
            - If possible, code is tested
            
            ## PR Description
            - is clear and concise
            - includes a summary of changes
            - (optional) includes a link to the issue that the PR is addressing
            
            ## Best Practices
            - Code follows best practices of the language / framework being used
            - Code is DRY (Don't Repeat Yourself)
            - Code is SOLID (Single Responsibility Principle, Open/Closed Principle, Liskov Substitution Principle, Interface Segregation Principle, Dependency Inversion Principle)
            
            # Review Structure & Format
            Use the following structure when formulating your review:
            
            Your changes look <overall sentiment>. You've <something positive>, but there is room for improvement in <...>:
            - Change <something> in <file> to <reason>
            - Class <class> could use <something>
            - <something> in file <file> could have <implications>
            - It is best practice to <do this>. Consider <change> in <file>
            - etc...
            
            Review the pull request!