name: "🛠️ Build Something"

on:
  workflow_dispatch:
    inputs:
      what-to-build:
        description: 'Specify what to build'
        required: true
      purpose:
        description: 'How does this benefit your project or the end user?'
        required: true

jobs:
  build_something:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Build Task
        uses: PR-Pilot-AI/smart-actions/plan-and-execute@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          task-description: |
            The project owner wants you to build something:

            ```
            ${{ github.event.inputs.what-to-build }}
            ```

            How this benefits the project or the end user:

            ```
            ${{ github.event.inputs.purpose }}
            ```

          expected-result: New and/or modified files according to the build instructions

