name: "🚀 Generate Workflow Documentation"

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Which workflow needs documentation?'
        required: true

jobs:
  execute_quick_task:
    runs-on: ubuntu-latest
    steps:
      - name: Document Workflow
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Look at `tools/quick-task/README.md` to see how the README file for the workflow should be structured.
            2. Read the workflow file `tools/${{ github.event.inputs.workflow }}/workflow.yaml` to understand the workflow.
            3. Create a README file in `tools/${{ github.event.inputs.workflow }}/README.md` similar to the one you read in step 1.
            4. Make sure the tool is listed in `index.yaml` and `README.md`.
