name: 🔄 Import Smart Workflow

on:
  workflow_dispatch:
    inputs:
      workflow-id:
        description: ID of the workflow to import
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Determine workflow file path
        id: filepath
        run: |
          if [ -f tools/${{ github.event.inputs.workflow-id }}/workflow.yaml ]; then
            echo "::set-output name=path::tools/${{ github.event.inputs.workflow-id }}/workflow.yaml"
          elif [ -f automations/${{ github.event.inputs.workflow-id }}/workflow.yaml ]; then
            echo "::set-output name=path::automations/${{ github.event.inputs.workflow-id }}/workflow.yaml"
          else
            echo "Path not found" && exit 1
          fi
      - name: Copy workflow file
        run: cp ${{ steps.filepath.outputs.path }} .github/workflows/${{ github.event.inputs.workflow-id }}.yaml
