name: "🛠 Quick Code Change"

on:
  workflow_dispatch:
    inputs:
      code-to-change:
        description: 'Specify the code or file to change.'
        required: true
      how-to-change-it:
        description: 'Describe how to change the code.'
        required: true

jobs:
  execute_code_change:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Code Change
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            Read the following code:
            ${{ inputs.code-to-change }}

            and change it in the following way:
            ${{ inputs.how-to-change-it }}
